### ISSUE TITLE
Automatic object mapper

### ISSUE THREAD

**Issue by yamin8000** [nats-io/jparse#11]
Perhaps you considered this as a low-level (in terms of architecture, not class) and didn't need it necessary but the Object mapping option is powerful indeed, however, writing object mapper for nested and big objects could be time-consuming and requires a lot of boilerplate code which is against the whole idea of this tool which is consuming less time.

**Comment by RichardHightower** [comment]
Object mapper is out of scope for this. They are useful. Boon (another parser that I wrote [a lot of] which was forked into Groovy) does object mapping. I don't plan on adding an object mapper at this time.
